name: register-environment

on:
  workflow_call:
    inputs:
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      env_yaml:
        required: true
        type: string
    secrets:
      creds:
        required: true

jobs:
  register-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.creds }}

      - run: |
          az extension add -n ml -y
          az extension update -n ml

      - name: Create/Update environment
        run: |
          az ml environment create \
            --file "${{ inputs.env_yaml }}" \
            --resource-group "${{ inputs.resource_group }}" \
            --workspace-name "${{ inputs.workspace_name }}"

